
services:
  # Serveur PHP-FPM
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/var
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root@database:3306/app?serverVersion=8.0
    restart: unless-stopped
  
  # Serveur web Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # Base de données MySQL
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    # Node.js pour le frontend (si nécessaire)
  node:
    image: node:18-alpine
    volumes:
      - .:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npx encore dev --watch"

volumes:
  database_data:
