name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Run on every branch push
  pull_request:
    branches:
      - '**'  # Run on every PR
  workflow_dispatch:  # Allows manual execution (used for deploy)

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    needs: phpstan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-interaction --no-progress

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml

  deploy:
    name: Manual Docker Deploy (Master Only)
    runs-on: ubuntu-latest
    needs: phpunit
    if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}